### ISSUE TITLE
Feature Request `.restart` command

### ISSUE THREAD

**Issue by scott-wyatt** [trailsjs/trailpack-repl#30]
It would be nice to use the REPL to restart an app. 
## Proposal
- `.restart` - should restart the web server.

**Comment by jaumard** [comment]
@tjwebb currently `.stop()` under the repl crash like this : 

```
debug: Unloading trailpack core
debug: Unloading trailpack repl
debug:  TypeError: Cannot read property 'reverse' of undefined
    at REPL.unload (/Users/jaumard/Downloads/testTrails/node_modules/trailpack-repl/index.js:84:9)
    at /Users/jaumard/Downloads/testTrails/node_modules/trails/index.js:107:37
    at Array.map (native)
    at TrailsApp.stop (/Users/jaumard/Downloads/testTrails/node_modules/trails/index.js:105:38)
    at repl:1:27
    at REPLServer.defaultEval (repl.js:254:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:77:13)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.<anonymous> (readline.js:341:12)
    at Array.forEach (native)
    at REPLServer.Interface._normalWrite (readline.js:340:11)
    at Socket.ondata (readline.js:87:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
debug: Unloading trailpack router
debug: Unloading trailpack express4
debug: Unloading trailpack waterline
debug: Unloading trailpack footprints
```

To do the `.restart` maybe something like you do with `trailpack-autoreload` will fit perfectly.
