### ISSUE TITLE
trailpack-repl is not working with node js 7.1

### ISSUE THREAD

**Issue by cesar2064** [trailsjs/trailpack-repl#40]
I have the following trails dependencies: 
```
    "express": "^4.14.0",
    "trailpack-bootstrap": "^1.0.1",
    "trailpack-core": "^1.0.1",
    "trailpack-express": "^1.0.14",
    "trailpack-gulp": "^1.0.2",
    "trailpack-repl": "^1.1.2",
    "trailpack-router": "^1.0.8",
    "trailpack-sequelize": "^1.1.1",
    "trails": "^1.1.0",
    "trails-controller": "^1.0.0",
    "trails-model": "^1.0.0",
    "trails-policy": "^1.0.2",
    "trails-service": "^1.0.0-beta-2",
```
After installed node js 7.1, the application couldn't start and throwed the following error:

`
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at exports.Console.Console.log (D:\Projects\hangman-game\node_modules\winston\lib\winston\transports\console.js:121:20)
    at transportLog (D:\Projects\hangman-game\node_modules\winston\lib\winston\logger.js:234:15)
    at D:\Projects\hangman-game\node_modules\winston\node_modules\async\lib\async.js:157:13
    at _each (D:\Projects\hangman-game\node_modules\winston\node_modules\async\lib\async.js:57:9)
    at Object.async.each (D:\Projects\hangman-game\node_modules\winston\node_modules\async\lib\async.js:156:9)
    at exports.Logger.Logger.log (D:\Projects\hangman-game\node_modules\winston\lib\winston\logger.js:246:9)
    at exports.Logger.target.(anonymous function) [as info] (D:\Projects\hangman-game\node_modules\winston\lib\winston\common.js:54:18)
    at Object.createServer (D:\Projects\hangman-game\node_modules\trailpack-express\lib\server.js:59:15)
    at Express.initialize (D:\Projects\hangman-game\node_modules\trailpack-express\index.js:46:30)
    at app.after.then (D:\Projects\hangman-game\node_modules\trails\lib\trailpack.js:58:26)
error: The application did not boot successfully.
error: Try increasing the loglevel to "debug" to learn more
(node:17252) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: This socket is closed
(node:17252) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit
 code.
(node:17252) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'removeAllListeners' of undefined
`

If I remove the trailpack-repl from the config/main.js, the application normally starts.
I also removed the node_modules folder and installed the packages again but the problem is still there.

**Comment by cesar2064** [comment]
The problem is caused by a node js issue present in the version 7.1, we have to wait for a new node js version or rollback to a previous version.
